// 'use client'
import { Manrope } from 'next/font/google'
import Navbar from './components/Navbar';
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry';
const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <ThemeRegistry>
          <Navbar></Navbar>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  )
}
